# Generated by Django 4.0.8 on 2023-03-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diasporaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencePostal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Agence', models.CharField(max_length=45, null=True)),
                ('Codique', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaysNationalite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pays', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PieceJoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('RefDossier', models.CharField(max_length=45, null=True)),
                ('PieceType', models.CharField(max_length=45, null=True)),
                ('PieceTypeImg', models.CharField(max_length=45, null=True)),
                ('PieceType1', models.CharField(max_length=45, null=True)),
                ('PieceTypeImg1', models.CharField(max_length=45, null=True)),
                ('DateCreation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_mois',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mois_nom', models.CharField(max_length=45, null=True)),
                ('mois_date_min', models.IntegerField(null=True)),
                ('mois_date_max', models.IntegerField(null=True)),
                ('mois_quinze', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCompte',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('typeCompte', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
